# Generated by Django 5.0.4 on 2024-05-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_follower_num_user_following_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Follow_Relation',
        ),
    ]
